Section "InputClass"
    Identifier "touchpad"
    Driver "libinput"
    MatchIsTouchpad "on"

    # 1. Enable Tapping
    Option "Tapping" "on"
    
    # 2. Acceleration: 0.2 (Float between -1 and 1)
    Option "AccelSpeed" "0.2"
    
    # 3. Natural Scrolling
    Option "NaturalScrolling" "true"
    
    # 4. Disable Horizontal Scrolling
    Option "HorizontalScrolling" "false"

    # 5. Disable touchpad while typing
    Option "DisableWhileTyping" "true"
EndSection

